#ifndef __GUICOLOR_H
#define __GUICOLOR_H

	/* Some colours */
#define       BUTTON_BG_COLOR 89
#define     BUTTON_TEXT_COLOR 224
#define          BAR_BG_COLOR 89
#define  BUTTON_BORDLOW_COLOR 0
#define BUTTON_BORDHIGH_COLOR 81
#define      BUTTON_LOW_COLOR 92
#define     BUTTON_HIGH_COLOR 86

	/* Define some default colours */
#define WIN_BORD_COLOR 106
#define WIN_BACK_COLOR 87
#define WIN_TEXT_COLOR 80
#define WIN_BORD_TEXT_COLOR 226
#define WIN_HIGH_COLOR 83
#define  WIN_LOW_COLOR 93

#define LIST_TEXT_COLOR 80
#define LIST_BACK_COLOR 0
#define LIST_BOLDTEXT_COLOR 0
#define LIST_BOLDBACK_COLOR 82
#define LIST_BORD_COLOR 107

#define  ERROR_WIN_TEXT WIN_TEXT_COLOR
#define    ERROR_WIN_BG WIN_BACK_COLOR
#define ERROR_WIN_TITLE 226
#define  ERROR_WIN_BORD 244

#define   MENU_BG_COLOR 87
#define MENU_TEXT_COLOR 80
#define MENU_BORD_COLOR 2
#define MENU_BGHIGH_COLOR 105
#define MENU_HIGH_COLOR 107
#define MENU_TEXTHIGH_COLOR 33


#endif				/* __GUICOLOR_H */